### ISSUE TITLE
Automate and Document wave deployment

### ISSUE THREAD

**Issue by munishchouhan** [seqeralabs/wave-k8s-deployment#1]
```[tasklist]
### Tasks
- [ ] Terraform script for deployment
- [ ] Document the steps of deployment
- [ ] recommenc=dations for customer
```
